# Generated by Django 3.2.7 on 2021-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tour_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours_image')),
                ('unexpired', models.BooleanField()),
            ],
        ),
    ]
