# Generated by Django 3.2.7 on 2021-09-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_tours_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=100, verbose_name='Имя')),
                ('kol', models.PositiveSmallIntegerField(default=1)),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.tour')),
            ],
        ),
    ]
