# Generated by Django 3.2.7 on 2021-09-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_tourregistration_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.tour'),
        ),
    ]
