# Generated by Django 3.2.7 on 2021-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_tourregistration_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
