# Generated by Django 3.2.7 on 2021-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_tourregistration_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
