# Generated by Django 3.2.7 on 2021-09-13 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0012_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourregistration',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tourregistration',
            name='user_name',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
