# Generated by Django 3.2.7 on 2021-09-13 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0013_auto_20210913_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourregistration',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tourregistration',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to=settings.AUTH_USER_MODEL),
        ),
    ]
