# Generated by Django 3.2.7 on 2021-09-14 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0014_auto_20210913_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='registered_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
