# Generated by Django 3.2.7 on 2021-09-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_tour_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='registered_users',
        ),
    ]
