# Generated by Django 3.2.7 on 2021-09-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_remove_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='tours_image'),
        ),
    ]
