# Generated by Django 3.2.7 on 2021-09-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
    ]
