# Generated by Django 3.2.7 on 2021-09-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_remove_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='customers.tour'),
        ),
    ]
