# Generated by Django 3.2.7 on 2021-09-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_auto_20210915_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='customers.tour')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
